(add-to-list 'load-path "~/.emacs.d/vendor")

(setq custom-file "~/.emacs.d/config/custom.el")
(load custom-file 'noerror)

(load "config/defuns")

;(vendor 'ruby-mode)
;(vendor 'rinari)
(vendor 'full-ack)
(vendor 'textmate)
;(vendor 'maxframe      'mf 'maximize-frame)
;(vendor 'filladapt)
;(vendor 'coffee-mode)
;(vendor 'haml-mode)
;(vendor 'sass-mode)
;(vendor 'htmlize)
;(vendor 'cdargs        'cv 'cdargs)
(vendor 'magit         'magit-status)
;(vendor 'psvn          'svn-status)
;(vendor 'js2-mode      'js2-mode)
;(vendor 'markdown-mode 'markdown-mode)
;(vendor 'textile-mode  'textile-mode)
;(vendor 'csv-mode      'csv-mode)
;(vendor 'yaml-mode     'yaml-mode)
;(vendor 'inf-ruby      'inf-ruby)
;(vendor 'rcodetools    'xmp)
;(vendor 'yasnippet)
;(vendor 'jekyll)
(vendor 'lua-mode      'lua-mode)
;(vendor 'feature-mode)
;(vendor 'mode-line-bell)
;(vendor 'revbufs       'revbufs)
(vendor 'shell-pop)
;(vendor 'mo-git-blame  'mo-git-blame-file 'mo-git-blame-current)
;(vendor 'ace-jump-mode 'ace-jump-mode 'ace-jump-word-mode 'ace-jump-char-mode 'ace-jump-line-mode)
;(vendor 'key-chord)

(vendor 'move-text)
(vendor 'vimrc-mode)
(vendor 'bookmark+)
(vendor 'dired+)
(vendor 'sunrise-commander)
(vendor 'smart-tab)
(vendor 'smex)
(vendor 'auto-highlight-symbol)
(vendor 'iedit)
(vendor 'goto-last-change)
(vendor 'autopair)
(vendor 'win-switch)
(vendor 'thingatpt+)
(vendor 'ido-ubiquitous)
;(vendor 'icicles)
(vendor 'nav)
(vendor 'mk-project)

;; (vendor 'ruby-electric 'ruby-electric-mode)
;; (vendor 'auctex)

(load "config/theme")
(load "config/env")
(load "config/global")
(load "config/tabs")
(load "config/disabled")
(load "config/fonts")
(load "config/utf-8")
(load "config/scratch")
(load "config/grep")
(load "config/diff")
(load "config/ido")
(load "config/dired")
(load "config/recentf")
(load "config/rectangle")
(load "config/org")
(load "config/zoom")
(load "config/flymake")
;(load "config/javascript")
;(load "config/ri-emacs")
(load "config/mac")
;(load "config/server-mode")
(load "config/shell-mode")
(load "config/shell-pop")
(load "config/ddx")
(load "config/ahs")
(load "config/smex")
(load "config/autopair")
(load "config/kill")
(load "config/winner")
(load "config/desktop")
(load "config/restore")
(load "config/sunrise")
(load "config/ibuffer")

(load "config/projects" 'noerror)
(load "config/private" 'noerror)

;; (load "config/hl-line")
;; (load "config/iswitchb")

;; Make sure bindings are set last to take precedence
(load "config/bindings")
