(add-to-list 'load-path "~/.emacs.d/vendor")

(setq custom-file "~/.emacs.d/config/custom.el")
(load custom-file 'noerror)

(load "config/defuns")

(vendor 'cl-lib)
(vendor 'packed)
(vendor 'auto-compile)
(load "config/auto-compile")

(vendor 'ace-jump-mode 'ace-jump-mode 'ace-jump-word-mode 'ace-jump-char-mode 'ace-jump-line-mode)
(vendor 'ack-and-a-half)
(vendor 'auto-complete)
(vendor 'auto-highlight-symbol)
(vendor 'autopair)
(vendor 'bookmark+)
(vendor 'browse-kill-ring)
(vendor 'dired+)
(vendor 'goto-last-change)
(vendor 'ido-ubiquitous)
(vendor 'iedit)
(vendor 'magit         'magit-status)
(vendor 'mk-project)
(vendor 'move-text)
(vendor 'nav)
(vendor 'paredit)
(vendor 'rainbow-delimiters)
(vendor 'refheap)
(vendor 'shell-pop)
(vendor 'smart-tab)
(vendor 'smex)
(vendor 'sr-speedbar)
(vendor 'sunrise-commander)
(vendor 'textmate)
(vendor 'thingatpt+)
(vendor 'undo-tree)
(vendor 'vimrc-mode)
(vendor 'win-switch)
(vendor 'workgroups)
(vendor 'xclip)

;; (vendor 'auctex)
;; (vendor 'cdargs        'cv 'cdargs)
;; (vendor 'csv-mode      'csv-mode)
;; (vendor 'full-ack)
;; (vendor 'icicles)
;; (vendor 'key-chord)
;; (vendor 'markdown-mode 'markdown-mode)
;; (vendor 'maxframe      'mf 'maximize-frame)
;; (vendor 'mo-git-blame  'mo-git-blame-file 'mo-git-blame-current)
;; (vendor 'psvn          'svn-status)
;; (vendor 'revbufs       'revbufs)
;; (vendor 'yasnippet)

(load "config/theme")
(load "config/env")
(load "config/global")

(load "config/ahs")
(load "config/auto-complete")
(load "config/autopair")
(load "config/ddx")
(load "config/desktop")
(load "config/diff")
(load "config/dired")
(load "config/disabled")
(load "config/flymake")
(load "config/fonts")
(load "config/grep")
(load "config/ibuffer")
(load "config/ido")
(load "config/kill")
(load "config/mac")
(load "config/org")
(load "config/recentf")
(load "config/rectangle")
(load "config/restore")
(load "config/scratch")
(load "config/shell-mode")
(load "config/shell-pop")
(load "config/smex")
(load "config/sunrise")
(load "config/tabs")
(load "config/utf-8")
(load "config/winner")
(load "config/workgroups")
(load "config/zoom")

(load "config/projects" 'noerror)
(load "config/private" 'noerror)

;; (load "config/server-mode")
;; (load "config/hl-line")
;; (load "config/iswitchb")

;; Make sure bindings are set last to take precedence
(load "config/bindings")
